### ISSUE TITLE
Project Submission

### ISSUE THREAD

**Issue by JKerb** [Java2Class/Project-3-Java-2-Programming#12]
Professor Pollock didn't specify when the project was due, however I think it's logical to believe he pushed the project to the next class day (Tuesday).  I would like to submit the project on Monday, if possible.  

Looking at the requirements for the project, I see two things we need: 

The Update Index button functionality is one of the things that we absolutely need for this project.  That is, it needs to be able to check the file/timestamp of each file in index.txt and verify that every last modified date in index.txt matches the last modified date of the actual files on the hard drive.  If hard drive files have been modified since the last run of the program, the button should refresh those timestamps in index.txt. (I don't know why we need to keep track of timestamps, but it's in the requirements.)  I guess this doesn't necessarily have to be a button.  It could be something done when the program starts (keeping user input out of it), but that's up to the one who works on it.

Another thing we need is the ability to view the files in the index outside of the Remove Files button (such as a dedicated View Indexed Files button).  This would be similar to the list used in Remove File, and could be a popup function.

Thanks.
Kerb

**Comment by JSilvey** [comment]
I am currently working on getting the incoming files stored into the program with the file name and date modified. This will store all files added so they are viewable even if you shut down and restart the program. Once I get this working correctly implementing the update button should be fairly easy (I hope). My goal is to have this working by the end of today.

John

**Comment by ChrisEngineer** [comment]
I just added the variable that will hold the string entered into the text field, also added the action listener for the enter key to use the search button. Which by the way apparently if I read correctly from what I was reading that the enter key is by default used but I set it to an actual button since it could infact use any key at that point

**Comment by JSilvey** [comment]
I finally got the index file figured out. I am sure there are better/easier ways to do it but I am exhausted. I've been fighting with this for the last 9 hours. It works on my end but I pushed it to my own branch until the main branch is fixed. I'll try to do more tomorrow concerning the update index button.

**Comment by scrizz** [comment]
I went ahead and commented out Chris' code. It was causing an error.
No one should push non working code to main (use a branch for test code)
![exts](https://cloud.githubusercontent.com/assets/1396042/6752789/a9296d32-cee7-11e4-8040-d9ab63ef67b5.png)

**Comment by JKerb** [comment]
It looks like, aside from a few optional bells and whistles, the project done.  I'm planning on submitting around noon tomorrow unless anyone has any objections.  Please let met know.

**Comment by JSilvey** [comment]
I'm done with my part for this portion of the project. Tomorrow noon submission is fine with me.

**Comment by scrizz** [comment]
I too am finished with this part of the project.
That is unless it breaks from now until tomorrow noon.
