### ISSUE TITLE
My Stuff

### ISSUE THREAD

**Issue by JSHaven** [Java2Class/Project-3-Java-2-Programming#13]
For some reason I wasn't able to push my work to the master. I got a lot of errors from Chris' work, so I'm not sure if it works or not, but I don't know how to fix it, so I can't push my work. I did push my work to Haven2. I added a file menu and I was trying to add a Directions Page (which I will edit a lot later). I will pick this up again Saturday. I may have to change the fast keys in the menu bar (ctrl+A [add index] and ctrl+C [clear fields] doesn't work until after the button is pressed). The items in the menu SHOULD function along with the buttons below.

**Comment by scrizz** [comment]
I'll look into it.

**Comment by scrizz** [comment]
You can go ahead and push your changes. Thanks for posting about the code.
