### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JSilvey** [Java2Class/Project-3-Java-2-Programming#17]
If someone has a spare few minutes would you mind testing my code on your machine. Make sure when you add a file and then exit the program the file is still there when you rerun the program. Also make sure it gets deleted when you remove the file. I did some quick testing on my end and it seems to work fine but it was late and I was tired so I want to make sure I didn't miss anything. Thanks
John

**Comment by scrizz** [comment]
tested working
