### ISSUE TITLE
My bug

### ISSUE THREAD

**Issue by JSilvey** [Java2Class/Project-3-Java-2-Programming#18]
Doing more testing today I found a bug in my code. If the file being added to the index has spaces in its path name (such as: "C:/users/john/my text file.txt") the file will get added fine to the index. However when the program is exited and the path is written to the index.txt file the added spaces mess up the scanner that tries to read in the file when the program is restarted. This results in an error and the program will not run. If this happens the line of text that displays the files path name and last modified time in the index.txt file needs to be deleted in order for the program to run. I do not have time to address this particular bug right now so for now just make sure any file you index does not contain any spaces in the path name. 
John

**Comment by scrizz** [comment]
I'll look into it a bit

**Comment by scrizz** [comment]
OK, I think I found a way to fix that.
essentially we'll be writing the String and Long each to a separate line.
and reading the Strings using nextLine() as opposed to next()

**Comment by scrizz** [comment]
fixed
