### ISSUE TITLE
My part...

### ISSUE THREAD

**Issue by ChrisEngineer** [Java2Class/Project-3-Java-2-Programming#19]
I'm still trying to figure out why the code did not work, I've read everything and tried to search it up and asked on StackOverflow, no help on there they want to pick apart other parts of the code and complain but not help with what my question. No worries though I only put the partial code that I'm dealing with on there... Yet the hunt to fix this before Monday still continues and if anyone has an idea on how to fix it please let me know sooner rather than later..

**Comment by scrizz** [comment]
post your code

**Comment by ChrisEngineer** [comment]
Does anyone else use Eclipse? I tried pushing it back to the branch I made yet the changes never hit the branch but it showed it pushed correctly
