### ISSUE TITLE
Suggested additions

### ISSUE THREAD

**Issue by JSilvey** [Java2Class/Project-3-Java-2-Programming#21]
I doubt we have time to implement these before turning in the project but I think it would enhance the search engine so I just want to see what you guys think. I can try to add them if I have time.
1. A button at the bottom to see a list all indexed files (currently the only way to see the indexed files is through the "remove file" button.) This button should just show a popup window of all files that are in the index with a simple close button to close the window.
2. Add a "remove all" button to the remove file window that allows the user to remove all files at once vs clicking through each file.
3. Leave the remove file window open until the user closes it instead of having it auto close after removing a file. 

Please add more if you think of them so we can implement them as we go.
John

**Comment by scrizz** [comment]
I've added the basic functionality. You guys can work on polish.

I'd like to see the ability to add more than one file at at time.

**Comment by JSilvey** [comment]
Those look great! Great Job!
