### ISSUE TITLE
Voice Mail Project

### ISSUE THREAD

**Issue by JKerb** [Java2Class/Project-3-Java-2-Programming#26]
I have read the instructions for the upcoming project several times.  Please correct me if I'm wrong, but it seems like the only thing we need to turn in for it is the following:

-Use Cases (Just a set of requirements containing what happens when the user interacts with the program)
-"any other documents" (optional?)

Under Description, the following requirements exist, which need to be expanded on with an (optional) decision tree:

USER
-Play back messages
-Delete messages
-Change the greeting
-Change the password

ADMIN
-Activate mailbox
-Deactivate mailbox
-Play message (own)
-Copy message (own)
-Play message (user)
-Copy message (user)

SYSTEM
-Remember messages (even with power failure)
-Back up messages
-Restore messages

He mentions that we are supposed to email him questions about it.  I don't see what the point of that is, since he is giving us the requirements.  What questions are we supposed to ask?

**Comment by scrizz** [comment]
You should add under the Admin the ability to play/copy other user messages

**Comment by JKerb** [comment]
Updated.

**Comment by scrizz** [comment]
I'm guessing the backup/restore is to/from some persistent storage.

**Comment by JKerb** [comment]
Yeah probably.  Within the company's file server or whatever (or a 3rd parties if they choose to go that route).  Maybe that's a question we need to ask about.

**Comment by scrizz** [comment]
I could see a DBMS being very handy in this situation.

**Comment by JKerb** [comment]
I made a decision tree for a basic system user in Visio.  Is something like this what we want to have for each use case (user/admin)?

![user decision tree](https://cloud.githubusercontent.com/assets/10632865/6887130/a45297a0-d623-11e4-8995-cde04a335874.png)

**Comment by scrizz** [comment]
That's excellent for users. I don't know if admins would have a mailbox too or just user management. This is another good question for the professor.

**Comment by scrizz** [comment]
For the use cases another flowchart may be used.

**Comment by JKerb** [comment]
Some questions for the email just straight from his slides and from above:
What are the # of users (total/average)

What are the performance requirements (message capacity)?

What are the the technology requirements?  Do you have your own servers or are they outsourced?  What operating systems do they use?

What are the operational requirements(uptime requirements/config files/toggle services)?

That's my two cents.

**Comment by JSilvey** [comment]
Hi Guys, I want to apologize for my lack of participation in this particular project thus far. I am preoccupied with my capstone project that is due on the 15th and I am a long way from being done. I plan on setting aside some time Sunday and Monday to do anything that may need to be finished for this project. Please let me know what needs to be finished or what i can do to help. Thanks 
John

**Comment by JKerb** [comment]
Haven is writing the proposal, might want to touch base with him and ask him if he needs anything.  Anyway, here is the admin decision tree.
![admin decision tree](https://cloud.githubusercontent.com/assets/10632865/6996900/477356e2-db72-11e4-9a07-8158de469cdf.png)

**Comment by scrizz** [comment]
I'm still waiting for a reply from the "contact"

@JKerb You might want to add a Copy and delete function under the message manager and a user selection(whose messages the admin is managing).

**Comment by JKerb** [comment]
In the use case I have the admin enter an identifier of the user whose messages he wishes to play and save.  

Isn't copy the same as save?  You're saving a message elsewhere, making a copy of it.  I can add a delete function, though.

For example, this is my Admin Save Message use case:

Use Case #14: Administrator Saves Message
    a. Administrator is prompted with authentication requirements.
    b. Administrator enters authentication.
    c. Program presents admin with Administrator Main Menu.
    d. Admin selects Messages Manager option.
    e. Program presents admin with Messages Manger menu.
    f. Admin selects Save Message function.
    g. Program prompts admin for account identifier.
    h. Admin enters account identifier.
    i. Program displays messages for specified account.
    j. Administrator selects messages for permanent storage.
    k. Program stores selected messages.
    l. Program presents admin with Mailbox Manager menu.

**Comment by scrizz** [comment]
Looks good.

**Comment by ChrisEngineer** [comment]
So I finished the updated Extreme Team Search Logo, but my scanner is not working, hoping that updating the thing will help out. If anything else I will bring it with me so you can all take a look at it and hopefully add it to the cover/fax cover to send in with the Project
