### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by JKerb** [Java2Class/Project-3-Java-2-Programming#27]
As you all know, the final portion of the search engine is due Thursday.  Please post below if you're working on a particular section.

**Comment by JKerb** [comment]
I can't even figure out how to check to see which radio button is selected.

**Comment by JKerb** [comment]
I am at a stopping point for today.  To summarize, I added a new class with methods to handle all of the searches we need.  I updated the search button action listener to forward everything needed to SearchManager.  Work needs to be done on the methods contained in SearchManager, focusing mainly on the meat of the project requirements, specifically the different types of searches we're doing.  I put the aMap in there so feel free to use it when trying to find the indexed files for reading and comparing.

**Comment by JSHaven** [comment]
I haven't done anything and I'm not sure what to do. I've been super busy from work (Lightning going to the playoffs.... yay e_e;) so if I can do something tonight just let me know, otherwise I got nothing lol

**Comment by scrizz** [comment]
K, I'll be working on the exact search.

**Comment by JKerb** [comment]
The only think left that is not completed/worked on is the all(AND) search on line 70 of the SearchManager class.

**Comment by JSilvey** [comment]
Unless I'm missing something it doesn't look like the files are actually being read in yet either. We are saving the file names and last modified dates but not actually reading in the contents. I will work on getting the contents of the text files into a searchable map. I will work on it late tonight and then again tomorrow. Can we wait to turn it in until just before class? I wont be able to start work on it tomorrow until about 1pm but I can work on it until about 6pm when I will need to leave to come to class. Thanks
John

**Comment by scrizz** [comment]
@JSilvey it does read the contents of the file. It reads them into an ArrayList.
try it out

**Comment by JSilvey** [comment]
lol I just tried it and it worked. I forgot the sound was up on my desktop pc and my wife just said,"What the hell was that?" when I clicked the search button. 

You are correct it is working. Okay so what can  I do now that I have competed my Capstone and can dedicate some time to this?

**Comment by scrizz** [comment]
@JSilvey you can give the AND(AKA "ALL") search method all your effort. :)

**Comment by JKerb** [comment]
LMAO the sound.

**Comment by scrizz** [comment]
make sure you guys pull the code as of 10:20pm

**Comment by JSilvey** [comment]
it found banana on my end before i pulled the newest code.

**Comment by JKerb** [comment]
Don't want the banana bug popping up.. woaah.

BTW I will submit this tomorrow before I go to class if you guys want, unless someone wants to submit it later.  I will be leaving the apartment around 2:00 or 3:00, so I will submit it around then.

**Comment by scrizz** [comment]
@JSilvey I changed quite a bit of the code in the project in my branch. Let me know if it affects you and how much. I won't create a pull request until I've heard back. :+1:

**Comment by JSilvey** [comment]
I'm having a hard time getting this portion to work. I need to get some sleep but I will continue working on it tomorrow. Please wait to turn it in until class time. The afternoon is the only chance I'll get to work on it. Thanks

**Comment by JKerb** [comment]
Okay, will do.  I'll leave it alone.

**Comment by scrizz** [comment]
Thanks

**Comment by JSHaven** [comment]
Hey, sorry for the lack of work this time around. With the Lightning going to the playoffs, it's been like one damn thing after another with little time to revise my schedule. So just gimme a zero. With these projects due in like 1 week, it makes it EXTREMELY difficult to do this, plus Unix, plus C# and other stuff. So, sorry for that. We need to talk about the next project, because I'm free this weekend so it'll be the best time for me to do something.

**Comment by JSilvey** [comment]
I just pushed the code I was working on. It will compile but it is just not working correctly for me. I've been looking at it for too long now. I tried.

**Comment by scrizz** [comment]
Np

**Comment by scrizz** [comment]
GG
