### ISSUE TITLE
Search header logo

### ISSUE THREAD

**Issue by scrizz** [Java2Class/Project-3-Java-2-Programming#4]
Testing this issue system and posting it from the github app on my phone. Lol

**Comment by ChrisEngineer** [comment]
I have done everything I can from home to try to push it back and it's not working, I've saved everything all the files to my thumb drive im going to have to do it from hcc

**Comment by scrizz** [comment]
No problem.

**Comment by scrizz** [comment]
Any update?

**Comment by ChrisEngineer** [comment]
Yea I'm actually having trouble uninstalling netbeans so I can reinstall it. It's giving me some file error sayin that something is in use when it's not but I'm on the way of fixing it I may just do a new install on my ssd drive and go from there

Sent using OWA for iPhone

**Comment by ChrisEngineer** [comment]
Ok Its been pushed. Let me know what you think of it

**Comment by JSilvey** [comment]
It doesn't work for me. There are now multiple errors and it wont run.

Exception in thread "main" java.lang.NullPointerException
    at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
    at searchui.UI.<init>(ui.java:27)
    at searchui.main.main(main.java:15)
Java Result: 1
BUILD SUCCESSFUL (total time: 1 second)

**Comment by ChrisEngineer** [comment]
I shall have to see what is wrong with it

Sent using OWA for iPhone

**Comment by JSilvey** [comment]
Where is this icon going? I can try to work with it and get it working also I just need to know where it is going to be placed? It looks like a rather large image.

**Comment by scrizz** [comment]
Fixed it.

**Comment by ChrisEngineer** [comment]
What was the problem the path name for the image?

Sent using OWA for iPhone

**Comment by scrizz** [comment]
path must be relative to the class.

On Tue, Feb 24, 2015 at 4:32 PM, Christopher Howard <
notifications@github.com> wrote:

> What was the problem the path name for the image?
> 
> Sent using OWA for iPhone
> 
> ---
> 
> From: Jair Garcia-Varela notifications@github.com
> Sent: Tuesday, February 24, 2015 2:26:22 PM
> To: Java2Class/Project-3-Java-2-Programming
> Cc: Howard, Christopher
> Subject: Re: [Project-3-Java-2-Programming] Search header logo (#4)
> 
> Fixed it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/Java2Class/Project-3-Java-2-Programming/issues/4#issuecomment-75826854
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Java2Class/Project-3-Java-2-Programming/issues/4#issuecomment-75850798
> .

## 

NOTICE OF CONFIDENTIALITY
This e-mail, and any attachment to it, contains company confidential and/or
privileged information intended only for the use of the individual(s) named
on the e-mail. If you are not the intended recipient, you are hereby
notified that any disclosure, copying or distribution of this information
or the taking of any action in reliance on the contents of this e-mail
transmission is strictly prohibited. If you have received this e-mail in
error, please notify the sender by telephone immediately, and/or
immediately return it to the sender, and delete it from your system.
Thank you for your cooperation.

**Comment by scrizz** [comment]
@JSilvey sorry I didn't see your message before.

**Comment by JSilvey** [comment]
No problem
